version: '3.8'


networks:
  freeport:
    external: true
services:
  api:
    container_name: freeport-crons
    image: freeport/freeport-crons
    restart: on-failure
    build:
        context: ./
        dockerfile: ./Dockerfile
    volumes:
        - ./:/app
    ports:
      - '6020:6020'
    networks:
      - freeport
