FROM python:3.11-rc-bullseye

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install cron

RUN touch /var/log/cron.log

RUN mkdir /app

WORKDIR /app

ADD . /app

RUN pip3 install -r requirements.txt

COPY cronfile.txt /etc/cron.d/cjob

RUN chmod 0644 /etc/cron.d/cjob

ENV PYTHONUNBUFFERED 1

CMD cron -f