FROM ubuntu:latest


RUN apt-get update -yq \
    && apt-get install -y python3-dev build-essential -yq \
    && apt-get -y install curl -yq \
    && apt-get -y install cron -yq \
    && apt-get -y install python3-pip -yq\
    && apt-get purge -y --auto-remove gcc python3-dev build-essential

RUN mkdir /app

COPY . /app

WORKDIR /app

COPY requirements.txt /app

RUN pip3 install -r requirements.txt

# Copy cron file file to the cron.d directory
COPY cronfile /etc/cron.d/cronfile

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/cronfile

# Apply cron job
RUN crontab /etc/cron.d/cronfile

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log

ENTRYPOINT ["cron", "-f"]